# Generated by Django 5.2.4 on 2025-09-25 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_configuracion_valorconfiguracion'),
        ('inventario', '0002_producto_iva_porcentaje_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='empresas.sucursal'),
        ),
    ]
