# Generated by Django 5.2.4 on 2025-09-25 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_configuracion_valorconfiguracion'),
        ('inventario', '0003_almacen_sucursal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='almacen',
            name='inventario__empresa_39028e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='almacen',
            unique_together={('empresa', 'sucursal', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['empresa', 'sucursal', 'nombre'], name='inventario__empresa_cd6fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['sucursal', 'nombre'], name='inventario__sucursa_a8a0be_idx'),
        ),
    ]
