# Generated by Django 5.2.4 on 2025-10-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_almacen_inventario__empresa_39028e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aplicar_ieps',
            field=models.BooleanField(default=False, verbose_name='Aplicar IEPS (8%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='aplicar_iva',
            field=models.BooleanField(default=True, verbose_name='Aplicar IVA (16%)'),
        ),
    ]
