# Generated by Django 5.2.4 on 2025-10-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_aplicar_ieps_producto_aplicar_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='afectastock',
            field=models.BooleanField(default=False, verbose_name='Afecta el stock'),
        ),
    ]
