# Generated by Django 5.2.4 on 2025-08-10 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_configuracion_valorconfiguracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento')),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto')], max_length=20, verbose_name='Tipo de descuento')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad disponible')),
                ('restantes', models.PositiveIntegerField(default=0, verbose_name='Usos restantes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_descuento', to='empresas.empresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_descuento_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Código de descuento',
                'verbose_name_plural': 'Códigos de descuento',
                'indexes': [models.Index(fields=['empresa', 'codigo'], name='ventas_codi_empresa_a8477f_idx')],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
