# Generated by Django 5.2.4 on 2025-10-15 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_convenio_cliente'),
        ('empresas', '0002_configuracion_valorconfiguracion'),
        ('inventario', '0005_producto_aplicar_ieps_producto_aplicar_iva'),
        ('planes', '0008_plan_costo_inscripcion'),
        ('ventas', '0002_venta_detalleventa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='importe',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='impuesto_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='impuesto_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='item_tipo',
            field=models.CharField(blank=True, choices=[('PLAN', 'PLAN'), ('PRODUCTO', 'PRODUCTO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='periodicidad',
            field=models.CharField(blank=True, choices=[('DIARIO', 'DIARIO'), ('SEMANAL', 'SEMANAL'), ('QUINCENAL', 'QUINCENAL'), ('MENSUAL', 'MENSUAL'), ('ANUAL', 'ANUAL')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='plan_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='plan_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='folio_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='impuesto_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='empresas.sucursal'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='uso_cfdi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_capturadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='uuid_cfdi',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='clientes.cliente'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['item_tipo'], name='ventas_deta_item_ti_512b67_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['folio'], name='ventas_vent_folio_f7143d_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal'], name='ventas_vent_sucursa_c70d15_idx'),
        ),
    ]
