# Generated by Django 5.2.4 on 2025-08-10 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_configuracion_valorconfiguracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('acceso_multisucursal', models.BooleanField(default=False, verbose_name='Acceso multisucursal')),
                ('tipo_plan', models.CharField(blank=True, max_length=50, verbose_name='Tipo de plan')),
                ('preventa', models.BooleanField(default=False, verbose_name='Preventa')),
                ('desde', models.DateField(blank=True, null=True, verbose_name='Vigente desde')),
                ('hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('visitas_gratis', models.PositiveIntegerField(default=0, verbose_name='Visitas gratis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='empresas.empresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RestriccionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('dia', models.CharField(max_length=20, verbose_name='Día')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='planes.plan', verbose_name='Plan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricciones_planes_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Restricción de plan',
                'verbose_name_plural': 'Restricciones de plan',
            },
        ),
        migrations.CreateModel(
            name='PrecioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('esquema', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal'), ('empresa', 'Empresa')], max_length=20, verbose_name='Esquema')),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('semanal', 'Semanal'), ('sesiones', 'Por sesiones')], max_length=20, verbose_name='Tipo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('numero_visitas', models.PositiveIntegerField(default=0, help_text='Si es 0, no se contabilizan visitas.', verbose_name='Número de visitas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='planes.plan', verbose_name='Plan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_planes_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Precio de plan',
                'verbose_name_plural': 'Precios de plan',
                'unique_together': {('plan', 'esquema', 'tipo')},
            },
        ),
    ]
