# Generated by Django 5.2.4 on 2025-08-19 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_caracteristica_convenio_datoadicional_datocontacto_and_more'),
        ('empresas', '0002_configuracion_valorconfiguracion'),
        ('planes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del beneficio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_descuento', models.CharField(blank=True, max_length=50, verbose_name='Tipo de descuento')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('unidad', models.IntegerField(default=0, help_text='Uso libre; 0 si no aplica', verbose_name='Unidad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='empresas.empresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('limite_personas', models.IntegerField(default=0, help_text='0 = sin límite', verbose_name='Límite de personas')),
                ('recomendaciones', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='empresas.empresa', verbose_name='Empresa')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas_impartidas', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('tipo_acceso', models.CharField(blank=True, max_length=50, verbose_name='Tipo de acceso')),
                ('numero_accesos', models.IntegerField(default=0, verbose_name='Número de accesos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_planes', to='planes.disciplina', verbose_name='Disciplina')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='planes.plan', verbose_name='Plan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Disciplina por plan',
                'verbose_name_plural': 'Disciplinas por plan',
            },
        ),
        migrations.CreateModel(
            name='HorarioDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='planes.disciplina', verbose_name='Disciplina')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Horario de disciplina',
                'verbose_name_plural': 'Horarios de disciplina',
            },
        ),
        migrations.CreateModel(
            name='PlanBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('vigencia_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Vigencia inicio')),
                ('vigencia_fin', models.DateTimeField(blank=True, null=True, verbose_name='Vigencia fin')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_planes', to='planes.beneficio', verbose_name='Beneficio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_incluidos', to='planes.plan', verbose_name='Plan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Beneficio del plan',
                'verbose_name_plural': 'Beneficios del plan',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='empresas.empresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='PlanServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('icono', models.CharField(blank=True, max_length=120, verbose_name='Icono')),
                ('fecha_baja', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_incluidos', to='planes.plan', verbose_name='Plan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_planes', to='planes.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicio del plan',
                'verbose_name_plural': 'Servicios del plan',
            },
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('tipo_acceso', models.CharField(max_length=20, verbose_name='Tipo de acceso')),
                ('puerta', models.CharField(blank=True, max_length=120, verbose_name='Puerta')),
                ('temperatura', models.FloatField(blank=True, null=True, verbose_name='Temperatura')),
                ('fecha', models.DateTimeField(verbose_name='Fecha/Hora de acceso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='empresas.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='empresas.sucursal', verbose_name='Sucursal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
                'indexes': [models.Index(fields=['empresa', 'sucursal', 'cliente', 'fecha'], name='planes_acce_empresa_c9a765_idx')],
            },
        ),
        migrations.CreateModel(
            name='AltaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de alta')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('renovacion', models.BooleanField(default=False, verbose_name='Renovación automática')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altas_plan', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altas_plan', to='empresas.empresa', verbose_name='Empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altas', to='planes.plan', verbose_name='Plan')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altas_plan', to='empresas.sucursal', verbose_name='Sucursal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Alta de plan',
                'verbose_name_plural': 'Altas de plan',
                'indexes': [models.Index(fields=['empresa', 'sucursal', 'cliente', 'plan'], name='planes_alta_empresa_2376c2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='beneficio',
            index=models.Index(fields=['empresa', 'nombre'], name='planes_bene_empresa_d8eb02_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplina',
            index=models.Index(fields=['empresa', 'nombre'], name='planes_disc_empresa_8ae326_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinaplan',
            index=models.Index(fields=['plan', 'disciplina'], name='planes_disc_plan_id_7c9a06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaplan',
            unique_together={('plan', 'disciplina')},
        ),
        migrations.AddIndex(
            model_name='horariodisciplina',
            index=models.Index(fields=['disciplina', 'hora_inicio', 'hora_fin'], name='planes_hora_discipl_1a6a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='planbeneficio',
            index=models.Index(fields=['plan', 'beneficio'], name='planes_plan_plan_id_5cb73e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planbeneficio',
            unique_together={('plan', 'beneficio')},
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['empresa', 'nombre'], name='planes_serv_empresa_46a6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='planservicio',
            index=models.Index(fields=['plan', 'servicio'], name='planes_plan_plan_id_c07363_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planservicio',
            unique_together={('plan', 'servicio')},
        ),
    ]
