# Generated by Django 5.2.4 on 2025-09-02 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_beneficio_disciplina_disciplinaplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fin', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_rel', to='planes.beneficio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_rel', to='planes.servicio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_beneficio_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beneficio de servicio',
                'verbose_name_plural': 'Beneficios de servicio',
                'unique_together': {('servicio', 'beneficio')},
            },
        ),
    ]
