# Generated by Django 5.2.4 on 2025-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_serviciobeneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='icono',
            field=models.CharField(blank=True, default='', help_text="Nombre del ícono (ej. 'Dumbbell')", max_length=64),
        ),
    ]
