# Generated by Django 5.2.4 on 2025-09-20 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_servicio_icono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('version', models.PositiveIntegerField(help_text='Versión incremental del plan')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('acceso_multisucursal', models.BooleanField(default=False)),
                ('tipo_plan', models.CharField(blank=True, max_length=50)),
                ('preventa', models.BooleanField(default=False)),
                ('visitas_gratis', models.PositiveIntegerField(default=0)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='planes.plan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
        ),
        migrations.CreateModel(
            name='PlanBeneficioRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('vigencia_inicio', models.DateTimeField(blank=True, null=True)),
                ('vigencia_fin', models.DateTimeField(blank=True, null=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.beneficio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_incluidos', to='planes.planrevision')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaPlanRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('tipo_acceso', models.CharField(blank=True, max_length=50)),
                ('numero_accesos', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.disciplina')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='planes.planrevision')),
            ],
        ),
        migrations.AddField(
            model_name='altaplan',
            name='plan_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='altas', to='planes.planrevision'),
        ),
        migrations.CreateModel(
            name='PlanServicioRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('icono', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_incluidos', to='planes.planrevision')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.servicio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioPlanRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('esquema', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal'), ('empresa', 'Empresa')], max_length=20)),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('semanal', 'Semanal'), ('sesiones', 'Por sesiones')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_visitas', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='planes.planrevision')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
        ),
        migrations.CreateModel(
            name='RestriccionPlanRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('dia', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='planes.planrevision')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='planrevision',
            index=models.Index(fields=['plan', 'version'], name='planes_plan_plan_id_ef82ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planrevision',
            unique_together={('plan', 'version')},
        ),
        migrations.AddIndex(
            model_name='planbeneficiorevision',
            index=models.Index(fields=['revision', 'beneficio'], name='planes_plan_revisio_fc45a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planbeneficiorevision',
            unique_together={('revision', 'beneficio')},
        ),
        migrations.AddIndex(
            model_name='disciplinaplanrevision',
            index=models.Index(fields=['revision', 'disciplina'], name='planes_disc_revisio_41dc85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaplanrevision',
            unique_together={('revision', 'disciplina')},
        ),
        migrations.AddIndex(
            model_name='planserviciorevision',
            index=models.Index(fields=['revision', 'servicio'], name='planes_plan_revisio_37e2a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planserviciorevision',
            unique_together={('revision', 'servicio')},
        ),
        migrations.AddIndex(
            model_name='precioplanrevision',
            index=models.Index(fields=['revision', 'esquema', 'tipo'], name='planes_prec_revisio_b3062e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precioplanrevision',
            unique_together={('revision', 'esquema', 'tipo')},
        ),
    ]
