# Generated by Django 5.2.4 on 2025-09-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_planrevision_planbeneficiorevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='altaplan',
            name='fecha_limite_pago',
            field=models.DateField(blank=True, db_index=True, help_text='Vencimiento para liquidar esta alta/pedido.', null=True, verbose_name='Fecha límite de pago'),
        ),
    ]
