# Generated by Django 5.2.4 on 2025-09-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0006_altaplan_fecha_limite_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='fecha_limite_pago',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha límite de pago'),
        ),
    ]
