# Generated by Django 5.2.4 on 2025-10-02 01:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0007_plan_fecha_limite_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='costo_inscripcion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto en MXN', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de inscripción'),
        ),
    ]
