# Generated by Django 5.2.4 on 2025-08-09 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=255, verbose_name='Contacto de emergencia')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('factura', models.BooleanField(default=False, verbose_name='¿Requiere factura?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('recordar_vencimiento', models.BooleanField(default=False, verbose_name='Recordar vencimiento')),
                ('recibo_pago', models.BooleanField(default=False, verbose_name='Enviar recibo de pago')),
                ('recibir_promociones', models.BooleanField(default=True, verbose_name='Recibir promociones')),
                ('genero', models.CharField(blank=True, max_length=20, verbose_name='Género')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
