# Generated by Django 5.2.4 on 2025-08-10 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('tipo_dato', models.TextField(verbose_name='Tipo de dato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='empresas.empresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('empresa_convenio', models.CharField(blank=True, max_length=255, verbose_name='Empresa del convenio')),
                ('telefono_oficina', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de oficina')),
                ('medio_entero', models.CharField(blank=True, max_length=120, verbose_name='¿Cómo se enteró?')),
                ('tipo_cliente', models.CharField(blank=True, max_length=120, verbose_name='Tipo de cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios_clientes', to='empresas.empresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
            },
        ),
        migrations.CreateModel(
            name='DatoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('campo', models.CharField(blank=True, max_length=255, verbose_name='Campo')),
                ('valor', models.CharField(blank=True, max_length=255, verbose_name='Valor')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='clientes.caracteristica', verbose_name='Característica')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_adicionales', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Dato adicional',
                'verbose_name_plural': 'Datos adicionales',
            },
        ),
        migrations.CreateModel(
            name='DatoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('tipo', models.CharField(choices=[('correo', 'Correo'), ('telefono', 'Teléfono'), ('celular', 'Celular'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_contacto', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Dato de contacto',
                'verbose_name_plural': 'Datos de contacto',
            },
        ),
        migrations.CreateModel(
            name='DatosFiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('rfc', models.CharField(blank=True, max_length=20, verbose_name='RFC')),
                ('razon_social', models.CharField(blank=True, max_length=255, verbose_name='Razón social')),
                ('persona', models.CharField(blank=True, choices=[('fisica', 'Persona Física'), ('moral', 'Persona Moral')], max_length=10, verbose_name='Tipo de persona')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('regimen_fiscal', models.CharField(blank=True, max_length=120, verbose_name='Régimen fiscal')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_fiscales', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Datos fiscales',
                'verbose_name_plural': 'Datos fiscales',
            },
        ),
        migrations.CreateModel(
            name='ClienteSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_asignadas', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_sucursales', to='empresas.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to='empresas.sucursal', verbose_name='Sucursal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Cliente por sucursal',
                'verbose_name_plural': 'Clientes por sucursal',
                'unique_together': {('cliente', 'sucursal', 'empresa')},
            },
        ),
    ]
