# Generated by Django 5.2.4 on 2025-09-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_caracteristica_convenio_datoadicional_datocontacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='esquema',
            field=models.CharField(max_length=20, null=True, verbose_name='Esquema'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_limite_pago',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha límite de pago'),
        ),
    ]
