# Generated by Django 5.2.4 on 2025-09-28 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_esquema_cliente_fecha_limite_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
