# Generated by Django 5.2.4 on 2025-10-23 12:46

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_convenio_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=clientes.models.cliente_avatar_upload_to, validators=[clientes.models.validate_image], verbose_name='Foto/Avatar'),
        ),
    ]
